### GET Request

GET http://localhost:1919/api                


### Request for  Register  a user AUTH/REGISTER

POST  http://localhost:1919/auth/register

Content-Type: application/application/json

{
    "username":"arjun@gmail.com",
    "password":"1234"
}

### Request for Login AUTH.LOGIN

POST   http://localhost:1919/auth/login

Content-Type: application/json

{
    "username":"arjun@gmail.com",
    "password":"1234"
}
