### GET

GET  http://localhost:5000/todo

### REGISTER NEW USERS WITH USERNAME AND PASSWORD

POST http://localhost:5000/auth/register
Content-Type:  application/json
{
    "userName":"arjun",
    "password":"arjun@gmail.com"
}

### LOGIN THE EXISTING USER WITH USERNAME AND PASSWORD

POST http://localhost:5000/auth/login
Content-Type: application/json
{
    "userName":"",
    "password":""
}